### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by zhyanlin** [wangjuan001/hicplus#1]
Hi,
May I know the memory requirement for executing hicplus? I tried to run
`hicplus pred_chromosome -i test.hic -m ../HiCplus_straw/model/pytorch_HindIII_model_40000 -c 19 22`
but failed due to memory error.

**Comment by wangjuan001** [comment]
Hi,
I suppose you need at least 30G to run the prediction. This version is still somehow hard coded. I set the Step size to 20M length, which means the prediction will take in the that size of chromosome as input at once.

**Comment by zhyanlin** [comment]
Thanks!
