### ISSUE TITLE
.hic format

### ISSUE THREAD

**Issue by MoPie** [wangjuan001/hicplus#2]
Hi Wangjuan,

May I ask what's the data structure for the input file (.hic). Would you mind provide a test.hic in your repository? We have difficulty access the  combined.hic you provide through Amazon aws.

Best,
Yixin

**Comment by wangjuan001** [comment]
Hi,
The test.hic means your own .hic file. It can be generated using [juicer](https://github.com/aidenlab/juicer) toolset. It's usually large in size and cannot be upload on github. For test purpose, maybe you can try the data from: [GSE98552](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE98552).

**Comment by MoPie** [comment]
> Hi,
> The test.hic means your own .hic file. It can be generated using [juicer](https://github.com/aidenlab/juicer) toolset. It's usually large in size and cannot be upload on github. For test purpose, maybe you can try the data from: [GSE98552](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE98552).

Thanks for your reply. I will try the data you provided later.
